version: '3.8'

services:
  pg-db:
    image: postgres:14.1
    container_name: polygonz-pg-db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
      - PG_DB_NAME
      - PG_DB_OWNER_USERNAME
      - PG_DB_OWNER_PASSWORD
      - PG_HOST
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./docker/.var/postgres/data:/var/lib/postgresql/data
      - ./docker/config/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    shm_size: '256m'

  pg-admin:
    image: dpage/pgadmin4:6.4
    container_name: polygonz-pg-admin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
      - PGADMIN_LISTEN_PORT
    ports:
      - 5001:5001
    volumes:
      - ./docker/.var/pgadmin:/var/lib/pgadmin
