#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
    CREATE USER ${PG_DB_OWNER_USERNAME} WITH PASSWORD '${PG_DB_OWNER_PASSWORD}';
    CREATE DATABASE ${PG_DB_NAME} WITH OWNER ${PG_DB_OWNER_USERNAME};
EOSQL
